// <auto-generated />
namespace OtraCosaStudio.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_film : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_film));
        
        string IMigrationMetadata.Id
        {
            get { return "202211161918309_add_film"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
